name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[FEATURE] '
labels: ['enhancement', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - Search functionality
        - API endpoints
        - React components
        - Configuration options
        - Performance optimization
        - Documentation
        - Developer experience
        - UI/UX improvements
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Significantly impacts my usage
        - Critical - Blocking my project
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature.
      placeholder: |
        - Use case 1: ...
        - Use case 2: ...
        - Use case 3: ...
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas on how this could be implemented?
      placeholder: If you have ideas on how this could be implemented, please share them here.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Any additional context, mockups, or examples that would help explain the feature.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following.
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a clear problem statement
          required: true
        - label: I have described my proposed solution
          required: true
        - label: I am willing to help implement this feature
          required: false

  - type: markdown
    attributes:
      value: |
        ## Related Issues
        Link any related issues here.
